CREATE TABLE IF NOT EXISTS todos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    assignee VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    deadline DATE NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE
);
